version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/job-hunting-api
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
